import io
from datetime import datetime
from collections import Counter

import openpyxl
from openpyxl.styles import Font
from fastapi import APIRouter, Depends, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from fastapi.templating import Jinja2Templates
from sqlalchemy.orm import Session

from app.database import get_db
from app.deps import get_current_user, get_current_range_state, get_active_serials
from app.models import User, SignalLog, RangeStateLog
from app.routers.dashboard import _latest_signal_status, _buzzer_active

router = APIRouter(prefix="/handover")
templates = Jinja2Templates(directory="app/templates")


def _handover_ctx(db: Session) -> dict:
    """Assemble a point-in-time snapshot of range state for shift handover."""
    range_state = get_current_range_state(db)
    active_serials = get_active_serials(db)

    serial_data = []
    total_up = 0
    any_buzzer = False
    for serial in active_serials:
        signals = _latest_signal_status(db, serial_id=serial.id)
        buzzer = _buzzer_active(signals, range_state)
        any_buzzer = any_buzzer or buzzer
        status_counts = Counter(s.signal_status for s in signals)
        total_up += status_counts.get("Up", 0)
        serial_data.append({
            "serial": serial,
            "signals": signals,
            "buzzer_active": buzzer,
            "status_counts": dict(status_counts),
        })

    recent_state_changes = (
        db.query(RangeStateLog).order_by(RangeStateLog.id.desc()).limit(8).all()
    )
    recent_notes = (
        db.query(SignalLog)
        .filter(SignalLog.is_deleted == False, SignalLog.entry_type == "Narrative")
        .order_by(SignalLog.timestamp.desc())
        .limit(8)
        .all()
    )

    return {
        "range_state": range_state,
        "serial_data": serial_data,
        "total_up": total_up,
        "any_buzzer": any_buzzer,
        "recent_state_changes": recent_state_changes,
        "recent_notes": recent_notes,
        "generated_at": datetime.utcnow(),
    }


@router.get("", response_class=HTMLResponse)
async def handover_view(
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return templates.TemplateResponse(request, "handover.html", {
        "user": current_user,
        "page": "handover",
        **_handover_ctx(db),
    })


@router.get("/print", response_class=HTMLResponse)
async def handover_print(
    request: Request,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    return templates.TemplateResponse(request, "handover_print.html", {
        "user": current_user,
        **_handover_ctx(db),
    })


def _fmt(dt: datetime | None) -> str:
    return dt.strftime("%Y-%m-%d %H:%M") if dt else ""


@router.get("/report.xlsx")
async def handover_report_xlsx(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Structured multi-sheet range report (Summary / Signals / State Changes / Notes)."""
    ctx = _handover_ctx(db)
    bold = Font(bold=True)
    wb = openpyxl.Workbook()

    # Summary
    ws = wb.active
    ws.title = "Summary"
    ws.append(["Range Report"]); ws["A1"].font = bold
    ws.append(["Generated (UTC)", _fmt(ctx["generated_at"])])
    ws.append(["Generated by", current_user.display_name])
    ws.append(["Range state", ctx["range_state"]])
    ws.append(["Signals up", ctx["total_up"]])
    ws.append(["Buzzer", "ACTIVE" if ctx["any_buzzer"] else "Off"])
    ws.append(["Active serials", len(ctx["serial_data"])])

    # Signals (one section of rows per active serial)
    ws = wb.create_sheet("Signals")
    headers = ["Serial", "Signal", "Status", "Band", "TxIF", "TxRF", "RxRF", "RxIF",
               "Unit", "Mod", "FEC", "Power", "Power Unit", "Source", "Antenna",
               "Last Update", "Operator"]
    ws.append(headers)
    for c in ws[1]:
        c.font = bold
    for sd in ctx["serial_data"]:
        for log in sd["signals"]:
            ws.append([
                sd["serial"].title, log.signal_name, log.signal_status, log.band,
                log.tx_if, log.tx_rf, log.rx_rf, log.rx_if, log.freq_unit,
                log.modulation, log.fec, log.power, log.power_unit, log.source,
                log.antenna, _fmt(log.timestamp),
                log.operator.display_name if log.operator else "",
            ])

    # State changes
    ws = wb.create_sheet("State Changes")
    ws.append(["Time", "From", "To", "By", "Reason"])
    for c in ws[1]:
        c.font = bold
    for rsc in ctx["recent_state_changes"]:
        ws.append([_fmt(rsc.timestamp), rsc.previous_state, rsc.new_state,
                   rsc.changed_by_user.display_name if rsc.changed_by_user else "", rsc.reason])

    # Notes
    ws = wb.create_sheet("Notes")
    ws.append(["Time", "Note", "By"])
    for c in ws[1]:
        c.font = bold
    for note in ctx["recent_notes"]:
        ws.append([_fmt(note.timestamp), note.notes,
                   note.operator.display_name if note.operator else ""])

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    stamp = ctx["generated_at"].strftime("%Y%m%d-%H%M")
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f"attachment; filename=range_report_{stamp}.xlsx"},
    )
